name: README Checker

on:
  push:
    branches:
      - main

jobs:
  check_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Verify README.md
      run: |
        # Look for the section title '8.4.2024'
        if grep -q '### 8.4.2024' README.md; then
          echo "Section '8.4.2024' found."
        else
          echo "Error: Section '8.4.2024' not found."
          exit 1
        fi

        # Check if there's a paragraph with at least 100 words
        paragraph=$(awk '/^### 8.4.2024/{flag=1;next}/^###/{flag=0}flag' README.md)
        word_count=$(echo $paragraph | wc -w)
        if [ "$word_count" -ge 100 ]; then
          echo "Paragraph contains $word_count words, greater than or equal to 100."
        else
          echo "Error: Paragraph contains only $word_count words, less than 100."
          exit 1
        fi

    - name: Set Commit Status
      if: always()
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const context = github.context;
          const octokit = new github.GitHub(process.env.GITHUB_TOKEN);

          const status = {
            ...context.repo,
            sha: context.sha,
            state: process.env.RESULT === 'success' ? 'success' : 'failure',
            target_url: 'https://github.com/Aequivinius/LA-demo/actions/runs/' + context.runId,
            description: process.env.RESULT === 'success' ? 'README checks passed' : 'README checks failed',
            context: 'README Checker'
          };

          await octokit.repos.createCommitStatus(status);
